### ISSUE TITLE
Virus 

### ISSUE THREAD

**Issue by seanlau2415** [beingfaisal/Car-Showroom-Management-System#1]
My Windows Defender has detected that your files contain a Trojan Spyware virus. Reported

**Comment by IsmailBenAli64** [comment]
My Windows Defender has detected that your files contain a Trojan Spyware virus too.

**Comment by ans-inayat** [comment]
password?

**Comment by ans-inayat** [comment]
Your app has entered a break state, but there is no code to show because all threads were executing external code (typically system or framework code).

**Comment by beingfaisal** [comment]
Windows defender is giving a false positive and as far as break state is concerned you probably dont have the right schema for project so when the app calls to database and does not receive a proper reply it breaks. I have already uploaded file containing schema and some helpful queries.

**Comment by beingfaisal** [comment]
> My Windows Defender has detected that your files contain a Trojan Spyware virus too.

This is a false positive given by windows defender. I have used Avira and Kaspersky to check the project and nothing was found

**Comment by ans-inayat** [comment]
Sign in user name and password

**Comment by beingfaisal** [comment]
> Sign in user name and password

You have to manually add manager(user) in your database and then you can sign in using that.

**Comment by ans-inayat** [comment]
How to add manually I was checking the assignment in the morning

**Comment by ans-inayat** [comment]
Please send me your WhatsApp number

**Comment by beingfaisal** [comment]
> Please send me your WhatsApp number

Email me at muhammadfaizal480@gmail.com and i will give you a detailed answer.
